spring:
  application:
    name: multiplication
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  datasource:
    url: jdbc:h2:file:~/multiplication;;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1;MODE=MySQL
    driverClassName: org.h2.Driver
    username: sa
    password: password
    platform: h2
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  error:
    include-message: always
    include-binding-errors: always

cors:
  allowedOrigins: http://localhost:3000